### ISSUE TITLE
query/params are not hydrated in client side routing

### ISSUE THREAD

**Issue by yairhaimo** [BDav24/next-url-prettifier#1]
When the "getInitialProps" function is called on the server side it receives the correct query params. When navigating to the page using the "Link" component the query does not receive the values of the route.

**Comment by BDav24** [comment]
Hi @yairhaimo 
Are the query params correctly set in the href of the object returned by `Router.linkPage(pageName, queryParams)`?

(Sorry for the delay, I didn't see the notification)
