### ISSUE TITLE
Library uses object.find, breaks in IE

### ISSUE THREAD

**Issue by vsaportas** [BDav24/next-url-prettifier#10]
I'm using this library and it's causing my project to crash in IE11, with a reference to line 39 of src/index.js:
`const route: ?RouteType<T> = this.routes.find((currentRoute: RouteType<T>): boolean =>`

The error is: 
`Object doesn't support property or method 'find'.`

Sorry I'm not totally clear how things fit together, but perhaps this library shouldn't use object.find in this way? Or perhaps it's on me to import this package in the right way to avoid this error. Would appreciate any guidance!

**Comment by BDav24** [comment]
You're right `find` is not available in IE. I replaced it with `filter` (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/filter), which is available since IE9.
Release: https://github.com/BDav24/next-url-prettifier/releases/tag/v1.1.6
