### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by ckeeney** [BDav24/next-url-prettifier#11]
Suppose I have a blog and I want both `/` and `/articles/:category` to route to `./pages/index.js`.

I tried this:
```js
    {
        page: 'index',
        prettyUrl: '/',
        prettyUrlPatterns: [
            {pattern: '/'},
            {pattern: '/articles/:category'}
        ]
    },
```

However, when you do 
```js
<Link {...Router.linkPage('index', {category: 'my-category'})} passHref><a>My Category</a></Link>
```
It just routes to `/`.  The correct way to do this is with 
```js
    {
        page: 'index',
        prettyUrl: ({category}) => category ? `article/${category}` : '/',
        prettyUrlPatterns: [
            {pattern: '/'},
            {pattern: '/articles/:category'}
        ]
    },
```

This should be clarified in the docs.

Specifically, is it true that `prettyUrl` is used for building the `as` prop and `prettyUrlPatterns` is used for path matching?

**Comment by BDav24** [comment]
Is it better? https://github.com/BDav24/next-url-prettifier/commit/0179ade2b50de7a69ae5d9e53d0c423c2604421e

**Comment by ckeeney** [comment]
Much better @BDav24.  Thanks for the library!
