### ISSUE TITLE
imperative routing

### ISSUE THREAD

**Issue by willmeierart** [BDav24/next-url-prettifier#12]
one thing unclear in documentation -- is imperative routing supported?
i.e. ```Router.prefetch()...etc```
if so, would you use the ```Router``` object imported from './server/routes' or from 'next/router'?
thanks! and great package btw

**Comment by BDav24** [comment]
Hi @willmeierart the next router is not exposed by this lib, so I'd go with `next/router`.

**Comment by willmeierart** [comment]
hey @BDav24, thanks for your quick response.

I don't want to clutter your repo with multiple issues, so I'll just put this here:
I'm trying to get one of the trickier parts of my app's routing to work (my main reason for using an external package), and the client-side routing is working great, however I'm throwing a 404 when I try to load on the server.

I'm specifically talking about the ```detail``` case here:

```
  {
    page: 'locations',
    title: 'Locations',
    prettyUrl: ({ state = '', spec = '' }) => {
      switch (state) {
        case 'initial':
          return '/locations'
        case 'results':
          if (spec && spec !== '') {
            return `/locations/results?search=${spec.toLowerCase().replace(/( )/g, '-')}`
          } else {
            return '/locations'
          }

        /* ...other cases... */

        case 'detail':
          if (spec && spec !== '') {
            return `/locations/${spec.toLowerCase().replace(/( )/g, '-')}`
          } else {
            return '/locations'
          }
        default:
          return '/locations'
      }
    },
    prettyUrlPatterns: [
      { pattern: '/locations', defaultParams: { state: 'initial' } },
      { pattern: '/locations/results?search=:spec', defaultParams: { state: 'results' } },

      /* ...other patterns... */

      { pattern: '/locations/detail/:spec', defaultParams: { state: 'detail' } }
    ]
  }
```

the main question being, is there just a problem with nested routes? or otherwise what am I missing to get the page to render correctly on the server-side. 

on a side note, if you notice the ```results``` case -- is there support for query strings (looking for reverse parseability)? I know path-to-regexp doesn't support query strings, and that probably the formatting is incorrect here, but curious if you know how I might approach parsing query strings. 

thanks for the help!

**Comment by BDav24** [comment]
@willmeierart 
Well, nested routes are not a problem if they're handled correctly by the lib or framework you use on the server side. An example with express: https://github.com/BDav24/next-url-prettifier/blob/master/examples/basic-with-express/server.js#L14-L16. Basically `Router.forEachPattern` is just a foreach on `prettyUrlPatterns` and you pass the function to apply if there is a match (usually call `next.render` for the page like in the next documentation: https://github.com/zeit/next.js/#custom-server-and-routing).

About query string, there is deliberately no support because formats may vary. You can use `qs` (https://github.com/BDav24/next-url-prettifier/blob/f4ede0602320700ba95294af7ba55c398881a5ca/examples/with-qs/routes.js) or any other.

About your router, have you considered splitting it by page?
```js
  [{
    page: 'locations/index',
    title: 'Location Search',
    prettyUrl: ({ spec = '' }) => {
      if (spec && spec !== '') {
        return `/locations/results?search=${spec.toLowerCase().replace(/( )/g, '-')}`
      } else {
        return '/locations'
      }
    },
    prettyUrlPatterns: [
      { pattern: '/locations', defaultParams: { state: 'initial' } },
      { pattern: '/locations/results?search=:spec', defaultParams: { state: 'results' } },
    ]
  }, {
    page: 'locations/detail',
    title: 'Location Detail',
    prettyUrl: ({ spec = '' }) => {
      return `/locations/detail/${spec.toLowerCase().replace(/( )/g, '-')}`
    },
    prettyUrlPatterns: [
      { pattern: '/locations/detail/:spec', defaultParams: { state: 'detail' } }
    ]
  }]
```
btw, there is a `detail` missing in the url of your `case`.

**Comment by willmeierart** [comment]
@BDav24 thanks so much man, super helpful answer.

**Comment by willmeierart** [comment]
@BDav24 to follow up,
+ that typo was the thing holding me up, the package is working great now 😅 - thanks for catching that!

+ curious though, referring to my initial question: I'm trying to use next/router to imperatively push route changes and having trouble. is there a conflict between the two?

My code looks like:
```
NextRouter.push({
  pathname: '/locations',
  query: {
     state: 'results',
     spec: place.formatted_address
                  .toLowerCase()
                  .replace(/(,)/g, '')
                  .replace(/( )/g, '-')
   },
   asPath: `/locations/results?search=${place.formatted_address}`,
   shallow: true
})
```
but I'm winding up with a url:
``` http://localhost:3000/locations?state=results&spec=2501-dallas-st-aurora-co-80010-usa ```, for example

I'm wondering, since ```props.url.asPath``` is logging as
``` /locations?state=results&spec=2501-dallas-st-aurora-co-80010-usa ``` if I'm just doing something wrong with next/router (although I've never had a problem getting it to work before)

...or if there is just a conflict between using the next native imperative router along with the custom express router I have set up along with next-url-prettifier.

thanks so much for the help and patience!

**Comment by BDav24** [comment]
@willmeierart 
Well I've never used `next/router`, but from their code I'd try something like that:

```js
NextRouter.push(
  { pathname: '/locations', query: ... },
  Router.linkPage('locations', { ... }).as, // edited: removed `/`
  { shallow: true }
)
```

**Comment by willmeierart** [comment]
edit: totally worked, with the only change of dropping the slash from the pathname inside ```linkPage```. you're awesome, thank you so much 🙏

**Comment by willmeierart** [comment]
a working component:

```
import NextRouter from 'next/router'
import { Router } from './routes'

const ImperativeRouter = {
  push: (path, query, shallow) =>
    NextRouter.push(
      {
        pathname: `/${path}`,
        query: query
      },
      Router.linkPage(path, query).as,
      { shallow }
    )
}

export default ImperativeRouter
```
cheers!

**Comment by a-barbieri** [comment]
For anyone coming to this thread, there is an important note to highlight.

### Pushing to a different page will force NextJS to reload the app from scratch 

This means for example that your **Redux state will be reset**.

Setting `shallow` to `true` won't help you as stated in [NextJS guidelines](https://github.com/zeit/next.js/tree/19f39511f42f8a5cdaef7e2066e70e30f9bac8ef#shallow-routing)

> Shallow routing works only for same page URL changes. For an example, let's assume we have another page called about, and you run this:
> 
> ```js
> Router.push('/?counter=10', '/about?counter=10', { shallow: true })
> ```
> Since that's a new page, it'll unload the current page, load the new one and call getInitialProps even though we asked to do shallow routing.
