### ISSUE TITLE
Pretty URL for custom Routes

### ISSUE THREAD

**Issue by Nickersona** [BDav24/next-url-prettifier#13]
I'm trying to use this module to replace a custom nextRoute I have in my application, but I'm running into issues divorcing the page property from the page file path in the case where.  Maybe I'm expecting a different thing from this library than it actually delivers, but here's my issue

I've got a route defined as such
``` javascript
{
        page: 'admin_users',
        prettyUrl: '/admin/users',
        prettyUrlPatterns: [
          { pattern: '/admin/users' },
        ]
    },
``` 

Server rendering works fine with the `Router.forEachPattern` But client side, if I call :
` Router.linkPage('admin_users')` I get `{ href: '/admin_users', as: '/admin/users' }` since it seems to be building the href from the page.

To which you might say, "just use the the file path as the page property", What I don't like about this, is that all the places where I call `linkPage()` I've coupled the file path to the route name which feels brittle to me. I'd like the freedom to re-organize my files system and updates the route definitions and have the rest of the code base be untouched.

Am I just using this library for the wrong thing? I'm kindof thinking this use case could be resolved by adding one additional property to the route definition called `path` that would be the path to whatever page file. It would default to the value of page, but could configured to the file path, and the page can be re-purposed as a page name to decouple a routes name from it's file path.

**Comment by BDav24** [comment]
In fact it's based on the way next/router works:
- `page`: tells next which page we're talking about (i.e. the path of your file)
- `prettyUrl` is the url used in the address bar

So the file path is necessary. In your case you don't even need to list the route, but if you do you can simplify:
```js
{
  page: 'admin/users'
}
```
