### ISSUE TITLE
incorrect peer dependency

### ISSUE THREAD

**Issue by andrewmclagan** [BDav24/next-url-prettifier#14]
`next-url-prettifier@1.2.0" has incorrect peer dependency "next@^4".`

although it works fine with next 6

**Comment by andrewmclagan** [comment]
see PR

https://github.com/BDav24/next-url-prettifier/pull/15

**Comment by BDav24** [comment]
Thanks @andrewmclagan , I used a broader:
```json
  "peerDependencies": {
    "next": ">= 1",
    "react": ">= 15"
  }
```
Seems to work.
