### ISSUE TITLE
`prettyUrl` and `prettyUrlPatterns` could be just `url` and `patterns`

### ISSUE THREAD

**Issue by a-barbieri** [BDav24/next-url-prettifier#16]
Would it be better if the configuration object had simpler keys?

Maybe `prettyUrl` and `prettyUrlPatterns` could be just `url` and `patterns`, couldn't be?

I'm available to make a PR if you think it's worthy.

**Comment by BDav24** [comment]
Hi @a-barbieri, the `pretty` prefix was a deliberate choice to show that these parameters are a little more than a simple `url`.
If you have a really long router configuration and `pretty` is really bothering you, I would do something like:

```js
const routes = [
  /* really long config with url and patterns... */
]

const urlPrettifier = new UrlPrettifier(routes.map(({ url, patterns, ...rest }) => {
  return { prettyUrl: url, prettyUrlPatterns: patterns, ...rest }
}))
```

**Comment by a-barbieri** [comment]
That sounds fair. 

But, just from a feedback perspective, the `pretty` prefix isn't helping developers so much to justify it (see [this other issue](https://github.com/BDav24/next-url-prettifier/issues/11)). It's not a problem of long keys, just a way to simplify and make the configuration code more self explanatory.

Said that, I'll stick with [your solution](
https://github.com/BDav24/next-url-prettifier/issues/16#issuecomment-430360595) which is a good compromise with the current version.

Thanks

**Comment by a-barbieri** [comment]
I was also thinking, for consistency's sake, shouldn't be `Router.linkPage()` rename to `Router.prettyLink()` using the `pretty` prefix or even better `Router.getPrettyUrl()` as you are trying to dynamically create the prettified url using the `prettyUrl` option in your routes?

**Comment by a-barbieri** [comment]
Same goes for `Router.forEachPattern()` could be `Router.getPrettyUrlPatterns()`.

This way is more explicit what the method refers to and viceversa what the object key is referring to.

BTW `get` could also be `generate` but then it's probably too verbose.

**Comment by BDav24** [comment]
Yes if you want you can create a pull request to add the alias methods `getPrettyUrl` and `forEachPrettyPattern`.

**Comment by a-barbieri** [comment]
How do we deal with deprecation? I was trying the following but I get a `no-console` lint error.

```
console.warn("linkPage() is deprecated. Use getPrettyUrl() instead.");
```

**Comment by a-barbieri** [comment]
I swear this is the last one.
If it is `forEachPrettyPattern`, can it be `prettyPattern` instead of `prettyUrlPattern`?
:-p

**Comment by BDav24** [comment]
For the lint error: `// eslint-disable-next-line no-console`

Yes `prettyPatterns` if you want.

**Comment by a-barbieri** [comment]
Update done. 

I've kept some test for the deprecated version of `prettyUrlPatterns` that can be ditched when you'll remove it entirely.

I've also updated the Readme.
