### ISSUE TITLE
Can I accomplish the same thing with Nextjs Routing?

### ISSUE THREAD

**Issue by garrettmac** [BDav24/next-url-prettifier#18]
All of these library for next Routing when nextjs has their own  Routing mechanisms seem to confuse me when trying to find the best solution for my problems.

My questions are:
1. Does it offer something that nextjs’s routing can’t do, or simply extend on ALL native routing that is already exists?
2. (Depending on 1) Can I still mix this with the native routing (I.e Dynamic routing and page/foo/[...rest] syntax?

**Comment by BDav24** [comment]
Well this lib is very simple : usually you pass `href` and (maybe) `as` to a `next/link`.
With `next-url-prettifier` you define your routes and when you call the helper `getPrettyUrl` (ex: `<Link route={Router.getPrettyUrl('greeting', {name, lang: switchLang})}>...`), you get an object containing `href` and `as` which is transmitted to `next/link` (https://github.com/BDav24/next-url-prettifier/blob/master/src/link.js#L25).

So:
1. It simply extends native routing.
2. You can use `next/link` along with this lib. Note: if you call `next-url-prettifier/Link` without `route` param, it will render a classic `next/link`.

**Comment by garrettmac** [comment]
v helpful thank you!
