### ISSUE TITLE
What is the difference between `prettyUrlPatterns` and `prettyPatterns`?

### ISSUE THREAD

**Issue by SilentImp** [BDav24/next-url-prettifier#19]
Hi,
I see both `prettyUrlPatterns` and `prettyPatterns`.
Also, there are `getPrettyUrlPatterns` and `getPrettyPatterns`.
But they seem similar. What is the difference between this two?

**Comment by BDav24** [comment]
Hi @SilentImp, from what I can see `prettyUrlPatterns` should be deprecated in favor of `prettyPatterns`: https://github.com/BDav24/next-url-prettifier/commit/104b394496af680e74ee71c8fe535d5fa30fa958
