### ISSUE TITLE
Add prefetch

### ISSUE THREAD

**Issue by hchoriq** [BDav24/next-url-prettifier#2]
Add prefetch to Link

**Comment by BDav24** [comment]
Hi @hchoriq, the link component of this lib passes all its props to the next link component:
`<Link {...this.props} {...route} />`

So the prefetch prop should work out of the box. If it's not working for you, you can reopen this issue.

Note: prefetch is a production only feature (source: https://github.com/zeit/next.js#prefetching-pages)
