### ISSUE TITLE
route prop passed to next/link

### ISSUE THREAD

**Issue by jedlikowski** [BDav24/next-url-prettifier#5]
Since one of the latest update to next 3 beta, propType checking has been introduced to next/link. This is when the following error in the console appeared:

`Warning: Failed prop type: Link: unknown props found: route in Link (created by PrettyLink)`

NextJS version: 3.0.1-beta.16

**Comment by BDav24** [comment]
Thanks for the heads-up, this should fix it: https://github.com/BDav24/next-url-prettifier/commit/32db37f2958a780481fd9b724fb3bb7a08e405ca

**Comment by jedlikowski** [comment]
@BDav24 should we have a new release with this fix?

**Comment by BDav24** [comment]
@jedlikowski Yes, already published: 1.1.5
