### ISSUE TITLE
Unknown props 'route' for 'Link' component

### ISSUE THREAD

**Issue by ShepelievD** [BDav24/next-url-prettifier#6]
I have the following code:

### file 'context/routes'
```
const urlPrettifier = new UrlPrettifier(routes)
export const buildUrl = (url, params) => urlPrettifier.linkPage(url, params)
```
### somewhere else
```
import { buildUrl } from 'context/routes'
...
<Link route={buildUrl('dashboard/retail/orders/show', { id: 123 })}>
  <CreateIcon style={style.icon} />
</Link>
...
```

It works but at the console, I see the following:
```
Warning: Failed prop type: Link: unknown props found: route
    in Link (created by PrettyLink)
    in PrettyLink (at TableRow.js:77)
    ....
```

Any ideas? Or maybe I do something wrong? Thanx

**Comment by BDav24** [comment]
Hi @ShepelievD what version of `next-url-prettifier` are you using?
This problem should have been fixed in version 1.1.5 (https://github.com/BDav24/next-url-prettifier/issues/5).

**Comment by ShepelievD** [comment]
@BDav24 I use 1.1.4

Thanx for a help! 👍

**Comment by BDav24** [comment]
You're welcome, keep me posted in case version `1.1.5` does not help.
