### ISSUE TITLE
Native Link

### ISSUE THREAD

**Issue by AndersDJohnson** [BDav24/next-url-prettifier#7]
Document or support native Next.js link by allowing spread of a function call to retrieve `href` and `as` props from an `href` string (and perhaps vice-versa). E.g.:
```js
import Link from 'next/link';

<Link {...Router.linkPage('greeting', {name: 'John'})}>
  click here
</Link>
```

```js
import Link from 'next/link';

<Link {...Router.link('/hello/John')}>
  click here
</Link>
```

**Comment by BDav24** [comment]
Hi @AndersDJohnson, I didn't test yet but your first example should work out of the box.
I'll test an document that when I get back from vacation.

**Comment by BDav24** [comment]
Here you go.

**Comment by AndersDJohnson** [comment]
@BDav24 Thanks. What about my `.link` example which accepts a string rather than a page and params? Could we reverse parse it? Might be more ergonomic.

**Comment by BDav24** [comment]
Do you have a more detailed example of what you need?

Because if you already have the final url, why not passing it directly to `next/link`?
```js
import Link from 'next/link'

<Link href="/hello/John">click here</Link>
```
